name: Configure Infrastructure

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set secret variable
        run: echo "SECRET"
      - name: Print secrets
        run: echo ${{ secrets.MY_SECRET }}
