name: Configure Infrastructure

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set secret variable
        id: test-task
        run: |
          MY_INLINE_SECRET="INLINESECRET"
          echo "::add-mask::$MY_INLINE_SECRET"
          echo "MY_INLINE_SECRET=$MY_INLINE_SECRET" >> "$GITHUB_OUTPUT"
      - name: Print secrets
        run: |
          echo "Secret set from UI: ${{ secrets.MY_SECRET }}"
          echo "Secret set in pipeline: $MY_INLINE_SECRET"
